import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { generateNocPdf, buildNocFileName, type NocEmployeeRow, type StampRectMeta } from '@/lib/noc-pdf';
import { resolveNocAssets } from '@/lib/noc-pdf-server';
import { ensureStorageDir, resolveStoragePath, slugify, uniqueFilePath } from '@/lib/document-storage';
import fs from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// /api/documents/noc/[id]/pdf?mode=inline|download
//   GET — serve the NOC PDF. SNAPSHOT MODEL:
//     · The stored file (filePath) is ALWAYS the unstamped as-issued PDF.
//     · When the NOC has a stamp enabled, the stamped version is rendered
//       ON THE FLY for inline preview and download — nothing is stamped on
//       disk at view time.
//     · mode=download with a stamp enabled additionally saves a SNAPSHOT of
//       exactly the stamped bytes delivered ("... (stamped).pdf", overwritten
//       on each stamped download) so the issued copy is auditable.
//     · If the base file is missing on disk (e.g. storage cleared) it is
//       regenerated byte-equivalently from the employee snapshot in the DB.
// ---------------------------------------------------------------------------

const stampedVariantName = (plain: string) => plain.replace(/\.pdf$/i, ' (stamped).pdf');

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const noc = await db.nocDocument.findFirst({ where: { id, deletedAt: null } });
    if (!noc) {
      return NextResponse.json({ success: false, error: 'NOC not found' }, { status: 404 });
    }
    // Drafts have no issued PDF — only finalized NOCs are served here.
    if (noc.status !== 'final') {
      return NextResponse.json({ success: false, error: 'This NOC is still a draft — preview it in the builder instead.' }, { status: 404 });
    }

    const mode = request.nextUrl.searchParams.get('mode');

    // ── resolve the UNSTAMPED base bytes ──
    // Prefer the preserved original, then the stored file (legacy rows may
    // still point filePath at a stamped rendition — normalized lazily below).
    let baseRel: string | null = null;
    if (noc.originalFilePath && fs.existsSync(resolveStoragePath(noc.originalFilePath))) {
      baseRel = noc.originalFilePath;
    } else if (noc.filePath && fs.existsSync(resolveStoragePath(noc.filePath))) {
      const looksStamped = noc.stampEnabled && noc.fileName.includes('(stamped)');
      baseRel = looksStamped ? null : noc.filePath;
    }

    let baseBytes: Buffer | null = null;
    if (baseRel) {
      try {
        const read = fs.readFileSync(resolveStoragePath(baseRel));
        if (read.length > 0) baseBytes = read;
        else baseRel = null;
      } catch {
        baseRel = null;
      }
    }

    if (!baseBytes) {
      // Regenerate the UNSTAMPED letter from the snapshot and re-persist so
      // future downloads are fast. (Never regenerated with the stamp — the
      // stored file must remain the unstamped original.)
      const employees = JSON.parse(noc.employeesJson || '[]') as NocEmployeeRow[];
      const assets = await resolveNocAssets({
        companyId: noc.companyId,
        stampId: noc.stampId,
        stampEnabled: false,
        stampType: noc.stampType,
        contactPerson: noc.contactPerson || null,
        contactPhone: noc.contactPhone || null,
        contactEmail: noc.contactEmail || null,
      });
      const pdfBytes = await generateNocPdf({
        clientName: noc.clientName,
        projectName: noc.projectName,
        clientAddress: noc.clientAddress,
        nocDate: noc.nocDate,
        contactPerson: assets.contactPerson,
        contactPhone: assets.contactPhone,
        contactEmail: assets.contactEmail,
        stampType: noc.stampType,
        stampEnabled: false,
        stampImagePath: undefined,
        letterheadPath: assets.letterheadPath,
        employees,
        bodyText: assets.bodyText,
        companyName: assets.companyName,
      });
      baseBytes = Buffer.from(pdfBytes);
      try {
        const dir = ensureStorageDir('noc', slugify(noc.clientName), noc.monthKey);
        const absPath = uniqueFilePath(dir, buildNocFileName({ clientName: noc.clientName, projectName: noc.projectName, nocDate: noc.nocDate }));
        fs.writeFileSync(absPath, baseBytes);
        baseRel = path.relative(process.cwd(), absPath).replace(/\\/g, '/');
        await db.nocDocument.update({
          where: { id },
          data: { filePath: baseRel, fileName: path.basename(absPath), originalFilePath: baseRel },
        });
      } catch (regenError) {
        console.error('NOC regeneration persist failed (serving bytes anyway):', regenError);
      }
    }

    // ── stamp decision ──
    let bytes = baseBytes;
    let fileName = noc.fileName || buildNocFileName({ clientName: noc.clientName, projectName: noc.projectName, nocDate: noc.nocDate });

    if (noc.stampEnabled) {
      const employees = JSON.parse(noc.employeesJson || '[]') as NocEmployeeRow[];
      const stampedMeta: { stampRect?: StampRectMeta | null } = {};
      let stampedBytes: Buffer | null = null;
      try {
        const assets = await resolveNocAssets({
          companyId: noc.companyId,
          stampId: noc.stampId,
          stampEnabled: true,
          stampType: noc.stampType,
          contactPerson: noc.contactPerson || null,
          contactPhone: noc.contactPhone || null,
          contactEmail: noc.contactEmail || null,
        });
        stampedBytes = Buffer.from(await generateNocPdf({
          clientName: noc.clientName,
          projectName: noc.projectName,
          clientAddress: noc.clientAddress,
          nocDate: noc.nocDate,
          contactPerson: assets.contactPerson,
          contactPhone: assets.contactPhone,
          contactEmail: assets.contactEmail,
          stampType: noc.stampType,
          stampEnabled: true,
          stampImagePath: assets.stampImagePath,
          letterheadPath: assets.letterheadPath,
          employees,
          bodyText: assets.bodyText,
          companyName: assets.companyName,
        }, stampedMeta));
      } catch (renderError) {
        // A corrupt/unreadable stamp image must never silently pass off an
        // unstamped PDF as stamped: DOWNLOAD fails loudly (the user is about
        // to keep this exact copy); inline preview falls back to the base so
        // the viewer keeps working — and it IS the unstamped original there.
        console.error('stamped render failed:', renderError);
        if (mode === 'download') {
          return NextResponse.json(
            { success: false, error: 'The stamp image file could not be read — re-upload the stamp in NOC Settings, then download again.' },
            { status: 400 },
          );
        }
        stampedBytes = null;
      }

      if (stampedBytes) {
        bytes = stampedBytes;
        fileName = stampedVariantName(fileName.replace(/\s*\(\s*stamped\s*\)\s*/i, ' ').replace(/\.pdf$/i, '') + '.pdf');

        if (mode === 'download') {
          // ── SNAPSHOT: persist exactly what is being delivered ──
          try {
            let dir: string;
            if (baseRel) {
              dir = path.dirname(resolveStoragePath(baseRel));
            } else {
              dir = ensureStorageDir('noc', slugify(noc.clientName), noc.monthKey);
            }
            const snapAbs = path.join(dir, stampedVariantName((noc.fileName || fileName).replace(/\s*\(\s*stamped\s*\)\s*/i, ' ').replace(/\.pdf$/i, '') + '.pdf'));
            // deterministic name → the snapshot is OVERWRITTEN, never accumulated
            fs.writeFileSync(snapAbs, stampedBytes);
            const snapRel = path.relative(process.cwd(), snapAbs).replace(/\\/g, '/');
            await db.nocDocument.update({
              where: { id },
              data: {
                stampSnapshotPath: snapRel,
                // keep the placement fresh for the animation / audits
                ...(stampedMeta.stampRect ? { stampRect: JSON.stringify(stampedMeta.stampRect) } : {}),
              },
            });
          } catch (snapError) {
            console.error('stamped snapshot persist failed (serving bytes anyway):', snapError);
          }
        } else if (stampedMeta.stampRect) {
          // inline preview discovered a fresher placement — persist quietly
          let storedJson = 'null';
          try { storedJson = JSON.stringify(JSON.parse(noc.stampRect || 'null')); } catch { /* keep null */ }
          const nextJson = JSON.stringify(stampedMeta.stampRect);
          if (storedJson !== nextJson) {
            await db.nocDocument.update({ where: { id }, data: { stampRect: nextJson } }).catch(() => undefined);
          }
        }
      }
    }

    const headers: Record<string, string> = {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `${mode === 'download' ? 'attachment' : 'inline'}; filename="${fileName.replace(/"/g, '')}"`,
      'Cache-Control': 'no-store',
    };
    return new NextResponse(new Uint8Array(bytes), { status: 200, headers });
  } catch (error) {
    console.error('GET /api/documents/noc/[id]/pdf error:', error);
    return NextResponse.json({ success: false, error: 'Failed to serve NOC PDF' }, { status: 500 });
  }
}
