import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { generateNocPdf, type NocEmployeeRow } from '@/lib/noc-pdf';
import { ensureStorageDir, resolveStoragePath, slugify, uniqueFilePath } from '@/lib/document-storage';
import fs from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// /api/documents/noc/[id]/pdf?mode=inline|download
//   GET — serve the stored NOC PDF. If the file is missing on disk (e.g.
//   storage was cleared) it is regenerated byte-for-byte from the employee
//   snapshot stored in the database.
// ---------------------------------------------------------------------------

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const noc = await db.nocDocument.findFirst({ where: { id, deletedAt: null } });
    if (!noc) {
      return NextResponse.json({ success: false, error: 'NOC not found' }, { status: 404 });
    }
    // Drafts have no issued PDF — only finalized NOCs are served here.
    if (noc.status !== 'final') {
      return NextResponse.json({ success: false, error: 'This NOC is still a draft — preview it in the builder instead.' }, { status: 404 });
    }

    let bytes: Buffer | null = null;

    if (noc.filePath) {
      const abs = resolveStoragePath(noc.filePath);
      if (fs.existsSync(abs)) {
        bytes = fs.readFileSync(abs);
      }
    }

    if (!bytes) {
      // Regenerate from the snapshot and re-persist so future downloads are fast
      const employees = JSON.parse(noc.employeesJson || '[]') as NocEmployeeRow[];
      const pdfBytes = await generateNocPdf({
        clientName: noc.clientName,
        projectName: noc.projectName,
        clientAddress: noc.clientAddress,
        nocDate: noc.nocDate,
        contactPerson: noc.contactPerson,
        contactPhone: noc.contactPhone,
        contactEmail: noc.contactEmail,
        stampType: noc.stampType,
        employees,
      });
      bytes = Buffer.from(pdfBytes);

      try {
        const dir = ensureStorageDir('noc', slugify(noc.clientName), noc.monthKey);
        const absPath = uniqueFilePath(dir, noc.fileName || 'NOC.pdf');
        fs.writeFileSync(absPath, bytes);
        const relativePath = path.relative(process.cwd(), absPath).replace(/\\/g, '/');
        await db.nocDocument.update({ where: { id }, data: { filePath: relativePath, fileName: path.basename(absPath) } });
      } catch (regenError) {
        console.error('NOC regeneration persist failed (serving bytes anyway):', regenError);
      }
    }

    const mode = request.nextUrl.searchParams.get('mode');
    const fileName = noc.fileName || 'NOC.pdf';
    const headers: Record<string, string> = {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `${mode === 'download' ? 'attachment' : 'inline'}; filename="${fileName.replace(/"/g, '')}"`,
      'Cache-Control': 'no-store',
    };
    return new NextResponse(new Uint8Array(bytes), { status: 200, headers });
  } catch (error) {
    console.error('GET /api/documents/noc/[id]/pdf error:', error);
    return NextResponse.json({ success: false, error: 'Failed to serve NOC PDF' }, { status: 500 });
  }
}
