'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Bell,
  AlertTriangle,
  Banknote,
  FileText,
  CheckCheck,
  Check,
  Clock,
  Plus,
  Search as SearchIcon,
  Loader2,
  UserCircle2,
  Sparkles,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';
import { useSettingsStore } from '@/store/settings-store';
import { formatMoney, getCurrencyDef } from '@/lib/currency';

/* ───────── types ───────── */


// Employee for dropdown
interface EmployeeOption {
  id: string;
  fullName: string;
  employeeId: string;
  phone: string | null;
  position: string | null;
  companyName: string | null;
  nationality: string | null;
  currentSite: string | null;
}

// Feed notification (from the Notification table)
interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'request' | 'warning' | 'fine' | 'agent';
  read: boolean;
  createdAt: string;
  updatedAt: string;
  actor?: { id: string; name: string; email: string; role: string } | null;
}

interface Warning {
  id: string;
  employeeId: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Fine {
  id: string;
  employeeId: string;
  reason: string;
  amount: number;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

/* ───────── helpers ───────── */

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatDateTime(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });
  } catch {
    return dateStr;
  }
}

function formatRelative(dateStr: string): string {
  try {
    const then = new Date(dateStr).getTime();
    const diff = Date.now() - then;
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return 'Just now';
    if (mins < 60) return `${mins}m ago`;
    const hours = Math.floor(mins / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    if (days < 7) return `${days}d ago`;
    return formatDate(dateStr);
  } catch {
    return dateStr;
  }
}

/* ───────── Skeleton Cards ───────── */
function SkeletonCards({ count = 3 }: { count?: number }) {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: count }).map((_, i) => (
        <Skeleton key={i} className="h-28 w-full rounded-xl bg-slate-700/50" />
      ))}
    </div>
  );
}

/* ───────── Empty State ───────── */
function EmptyState({ icon: Icon, message }: { icon: React.ElementType; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-700/50 mb-4">
        <Icon className="h-7 w-7 text-slate-500" />
      </div>
      <p className="text-sm text-slate-400">{message}</p>
    </div>
  );
}

/* ───────── Feed notification type visuals ───────── */
const NOTIF_TYPE_META: Record<string, { icon: React.ElementType; avatarClass: string; badgeClass: string; label: string }> = {
  agent: {
    icon: Sparkles,
    avatarClass: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    badgeClass: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/30',
    label: 'AI Assistant',
  },
  warning: {
    icon: AlertTriangle,
    avatarClass: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    badgeClass: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
    label: 'Warning',
  },
  fine: {
    icon: Banknote,
    avatarClass: 'bg-red-500/15 text-red-400 border-red-500/30',
    badgeClass: 'bg-red-500/15 text-red-300 border-red-500/30',
    label: 'Fine',
  },
  request: {
    icon: FileText,
    avatarClass: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    badgeClass: 'bg-blue-500/15 text-blue-300 border-blue-500/30',
    label: 'Request',
  },
};

/* ───────── Employee Search Combobox (reused) ───────── */
function EmployeeSearchCombobox({
  employees,
  onSelect,
  selectedId,
}: {
  employees: EmployeeOption[];
  onSelect: (emp: EmployeeOption) => void;
  selectedId: string | null;
}) {
  const [open, setOpen] = useState(false);
  const selectedEmployee = useMemo(
    () => employees.find((e) => e.id === selectedId),
    [employees, selectedId]
  );

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between bg-slate-800 border-slate-700 text-white hover:bg-slate-700 hover:text-white text-sm"
        >
          {selectedEmployee
            ? `${selectedEmployee.fullName} (${selectedEmployee.employeeId})`
            : 'Search employees...'}
          <SearchIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0 bg-slate-800 border-slate-600" align="start">
        <Command className="bg-slate-800">
          <CommandInput placeholder="Type to search..." className="text-white" />
          <CommandList>
            <CommandEmpty className="text-slate-400">No employees found.</CommandEmpty>
            <CommandGroup>
              {employees.map((emp) => (
                <CommandItem
                  key={emp.id}
                  value={`${emp.fullName} ${emp.employeeId} ${emp.position || ''}`}
                  onSelect={() => {
                    onSelect(emp);
                    setOpen(false);
                  }}
                  className="text-slate-200 data-[selected=true]:bg-slate-700 data-[selected=true]:text-white"
                >
                  <div className="flex flex-col">
                    <span className="text-sm">{emp.fullName}</span>
                    <span className="text-[11px] text-slate-500">
                      {emp.employeeId}
                      {emp.position ? ` · ${emp.position}` : ''}
                    </span>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

/* ───────── Alerts Tab (the notification feed) ───────── */
function AlertsTab({
  notifications,
  loading,
  onMarkRead,
  markingId,
}: {
  notifications: Notification[];
  loading: boolean;
  onMarkRead: (id: string) => void;
  markingId: string | null;
}) {
  if (loading) return <SkeletonCards />;
  if (notifications.length === 0) return <EmptyState icon={Bell} message="No notifications yet" />;

  return (
    <div className="flex flex-col gap-3">
      {notifications.map((n) => {
        const meta = NOTIF_TYPE_META[n.type] || NOTIF_TYPE_META.request;
        const TypeIcon = meta.icon;
        const issuerLabel =
          n.actor?.name
            ? n.actor.name
            : n.type === 'request'
            ? null
            : 'System';

        return (
          <div
            key={n.id}
            className={cn(
              'rounded-xl border p-4 transition-colors',
              n.read
                ? 'bg-slate-800/60 border-slate-700/60'
                : 'bg-slate-800 border-blue-500/40 shadow-[0_0_0_1px_rgba(59,130,246,0.15)]'
            )}
          >
            <div className="flex items-start gap-3.5">
              {/* Type avatar */}
              <div className={cn('flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border', meta.avatarClass)}>
                <TypeIcon className="h-5 w-5" />
              </div>

              {/* Body */}
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-2 flex-wrap min-w-0">
                    {!n.read && <span className="h-2 w-2 shrink-0 rounded-full bg-blue-400 animate-pulse" aria-label="Unread" />}
                    <h3 className={cn('text-base leading-snug truncate', n.read ? 'text-slate-200 font-semibold' : 'text-white font-semibold')}>
                      {n.title}
                    </h3>
                    <Badge variant="outline" className={cn('text-[11px] px-2 py-0 h-5 shrink-0', meta.badgeClass)}>
                      {meta.label}
                    </Badge>
                  </div>
                  <span className="text-xs text-slate-500 shrink-0 whitespace-nowrap" title={formatDateTime(n.createdAt)}>
                    {formatRelative(n.createdAt)}
                  </span>
                </div>

                <p className={cn('mt-1.5 text-sm leading-relaxed', n.read ? 'text-slate-400' : 'text-slate-200')}>
                  {n.message}
                </p>

                <div className="mt-2.5 flex items-center justify-between gap-3 flex-wrap">
                  <div className="flex items-center gap-4 flex-wrap text-xs text-slate-400">
                    {issuerLabel && (
                      <span className="inline-flex items-center gap-1.5">
                        <UserCircle2 className="h-3.5 w-3.5 text-slate-500" />
                        <span className="text-slate-500">Issued by</span>
                        <span className="font-medium text-slate-300">{issuerLabel}</span>
                      </span>
                    )}
                    <span className="inline-flex items-center gap-1.5 text-slate-500">
                      <Clock className="h-3.5 w-3.5" />
                      {formatDateTime(n.createdAt)}
                    </span>
                  </div>

                  {/* Per-item action */}
                  {n.read ? (
                    <span className="inline-flex items-center gap-1.5 text-xs text-slate-500 pr-1">
                      <Check className="h-3.5 w-3.5 text-emerald-400" />
                      Read
                    </span>
                  ) : (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => onMarkRead(n.id)}
                      disabled={markingId === n.id}
                      className="h-8 border-blue-500/40 bg-blue-500/10 text-blue-300 hover:bg-blue-500/20 hover:text-blue-200 text-xs gap-1.5"
                    >
                      {markingId === n.id ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <CheckCheck className="h-3.5 w-3.5" />
                      )}
                      Mark as read
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

/* ───────── Warnings Tab ───────── */
function WarningsTab({ userId }: { userId: string }) {
  const [warnings, setWarnings] = useState<Warning[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchWarnings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/warnings');
      const data = await res.json();
      if (data.success) {
        setWarnings(data.data.warnings || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch warnings', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchWarnings(); }, [fetchWarnings]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim()) {
      toast({ title: 'Validation Error', description: 'Please select an employee and provide a reason.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/warnings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Warning Issued', description: `Warning has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchWarnings();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue warning', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue warning', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-9 bg-orange-600 hover:bg-orange-700 text-white text-sm gap-1.5">
          <Plus className="h-4 w-4" /> Add New Warning
        </Button>
      </div>
      {loading ? <SkeletonCards /> : warnings.length === 0 ? <EmptyState icon={AlertTriangle} message="No warnings found" /> : (
        warnings.map(w => (
          <div key={w.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex items-start gap-3.5">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-orange-500/15 border-orange-500/30 text-orange-400">
                <AlertTriangle className="h-5 w-5" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                  <span className="text-base font-semibold text-white truncate">{w.employee.fullName}</span>
                  <Badge variant="outline" className="text-[11px] font-mono px-2 py-0 border-slate-600 text-slate-400">{w.employee.employeeId}</Badge>
                  {w.isAutoGenerated && <Badge className="text-[11px] px-2 py-0 h-5 bg-amber-500/20 text-amber-300 border border-amber-500/30">Auto</Badge>}
                </div>
                <p className="text-sm text-slate-300 leading-relaxed">{w.reason}</p>
                {w.absentDates && (
                  <p className="mt-1 text-sm text-slate-400"><span className="text-slate-500">Absent dates:</span> {w.absentDates}</p>
                )}
                <div className="mt-2.5 flex items-center justify-between gap-3 flex-wrap">
                  <div className="flex items-center gap-4 flex-wrap text-xs text-slate-400">
                    {/* Auto warnings are generated by the system — never credit a person */}
                    {w.isAutoGenerated ? (
                      <span className="inline-flex items-center gap-1.5">
                        <UserCircle2 className="h-3.5 w-3.5 text-slate-500" />
                        <span className="text-slate-500">Issued by</span>
                        <span className="font-medium text-slate-300">System (auto)</span>
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1.5">
                        <UserCircle2 className="h-3.5 w-3.5 text-slate-500" />
                        <span className="text-slate-500">Issued by</span>
                        <span className="font-medium text-slate-300">{w.createdBy?.name || 'Unknown'}</span>
                      </span>
                    )}
                    <span className="inline-flex items-center gap-1.5 text-slate-500">
                      <Clock className="h-3.5 w-3.5" />
                      {formatDateTime(w.createdAt)}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Warning Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Warning</DialogTitle>
            <DialogDescription>Issue a warning to an employee. This will deduct 0.5 stars from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the warning" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim()} className="bg-orange-600 hover:bg-orange-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Warning'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Fines Tab ───────── */
function FinesTab({ userId }: { userId: string }) {
  const { settings } = useSettingsStore();
  const currency = settings.currency;
  const currencyDef = getCurrencyDef(currency);

  const [fines, setFines] = useState<Fine[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [amount, setAmount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchFines = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/fines');
      const data = await res.json();
      if (data.success) {
        setFines(data.data.fines || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch fines', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchFines(); }, [fetchFines]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    setAmount('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim() || !amount) {
      toast({ title: 'Validation Error', description: 'Please fill in all required fields.', variant: 'destructive' });
      return;
    }
    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount < 0) {
      toast({ title: 'Invalid Amount', description: 'Amount must be a positive number.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/fines', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, amount: numAmount, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Fine Issued', description: `Fine of ${formatMoney(numAmount, currency)} has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchFines();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue fine', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue fine', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-9 bg-red-600 hover:bg-red-700 text-white text-sm gap-1.5">
          <Plus className="h-4 w-4" /> Add New Fine
        </Button>
      </div>
      {loading ? <SkeletonCards /> : fines.length === 0 ? <EmptyState icon={Banknote} message="No fines found" /> : (
        fines.map(f => (
          <div key={f.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex items-start gap-3.5">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border bg-red-500/15 border-red-500/30 text-red-400">
                <Banknote className="h-5 w-5" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                  <span className="text-base font-semibold text-white truncate">{f.employee.fullName}</span>
                  <Badge variant="outline" className="text-[11px] font-mono px-2 py-0 border-slate-600 text-slate-400">{f.employee.employeeId}</Badge>
                  <Badge className="text-[11px] px-2 py-0 h-5 font-semibold bg-red-500/20 text-red-300 border border-red-500/30">{formatMoney(f.amount, currency)}</Badge>
                </div>
                <p className="text-sm text-slate-300 leading-relaxed">{f.reason}</p>
                <div className="mt-2.5 flex items-center justify-between gap-3 flex-wrap">
                  <div className="flex items-center gap-4 flex-wrap text-xs text-slate-400">
                    <span className="inline-flex items-center gap-1.5">
                      <UserCircle2 className="h-3.5 w-3.5 text-slate-500" />
                      <span className="text-slate-500">Issued by</span>
                      <span className="font-medium text-slate-300">{f.createdBy?.name || 'Unknown'}</span>
                    </span>
                    <span className="inline-flex items-center gap-1.5 text-slate-500">
                      <Clock className="h-3.5 w-3.5" />
                      {formatDateTime(f.createdAt)}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Fine Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Fine</DialogTitle>
            <DialogDescription>Issue a fine to an employee. This will deduct 1 star from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              {/* Currency label follows the global app setting (dirhams by default) */}
              <Label>Amount ({currencyDef.code} — {currencyDef.name})</Label>
              <Input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" className="bg-slate-900 border-slate-700 text-white" />
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the fine" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim() || !amount} className="bg-red-600 hover:bg-red-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Fine'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Main Page ───────── */
export function NotificationPage() {
  const { user } = useAuthStore();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [markingId, setMarkingId] = useState<string | null>(null);
  const userId = user?.id || '';

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await fetch('/api/notifications?limit=100');
      const data = await res.json();
      if (data.success) {
        const notifs: Notification[] = data.data.notifications || [];
        setNotifications(notifs);
        setUnreadCount(notifs.filter((n) => !n.read).length);
      }
    } catch { } finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchNotifications(); }, [fetchNotifications]);

  const notifySidebarRefresh = () => {
    // Sidebar badge listens for this — unread count updates instantly.
    window.dispatchEvent(new Event('asm:refresh-badge-counts'));
  };

  const handleMarkRead = async (id: string) => {
    setMarkingId(id);
    // Optimistic: flip the item immediately, reconcile on failure.
    const prev = notifications;
    const wasUnread = prev.some((n) => n.id === id && !n.read);
    setNotifications((list) => list.map((n) => (n.id === id ? { ...n, read: true } : n)));
    if (wasUnread) setUnreadCount((c) => Math.max(0, c - 1));
    try {
      const res = await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id }),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      toast({ title: 'Notification marked as read' });
      notifySidebarRefresh();
    } catch {
      setNotifications(prev); // revert on failure
      setUnreadCount(prev.filter((n) => !n.read).length);
      toast({ title: 'Error', description: 'Failed to mark notification as read', variant: 'destructive' });
    } finally {
      setMarkingId(null);
    }
  };

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ markAll: true }) });
      setNotifications(prev => prev.map(n => ({ ...n, read: true })));
      setUnreadCount(0);
      toast({ title: 'All notifications marked as read' });
      notifySidebarRefresh();
    } catch { toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' }); }
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10"><Bell className="h-5 w-5 text-blue-400" /></div>
          <div><h2 className="text-2xl font-bold text-white flex items-center gap-2">Notifications{!loading && unreadCount > 0 && <Badge className="bg-blue-500 text-white">{unreadCount}</Badge>}</h2><p className="text-slate-400 text-sm">Stay updated with warnings, fines and requests</p></div>
        </div>
        {unreadCount > 0 && <Button variant="outline" size="sm" onClick={handleMarkAllRead} className="h-8 border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 text-xs"><CheckCheck className="h-3.5 w-3.5 mr-1.5" />Mark All Read</Button>}
      </div>

      <Tabs defaultValue="alerts" className="w-full">
        <TabsList className="bg-slate-800 border border-slate-700/50">
          <TabsTrigger value="alerts" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><Bell className="h-4 w-4" />Alerts{unreadCount > 0 && <Badge className="bg-blue-500 text-white ml-1 text-[10px] px-1.5 py-0 h-4">{unreadCount}</Badge>}</TabsTrigger>
          <TabsTrigger value="warnings" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><AlertTriangle className="h-4 w-4" />Warnings</TabsTrigger>
          <TabsTrigger value="fines" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><Banknote className="h-4 w-4" />Fines</TabsTrigger>
        </TabsList>

        <TabsContent value="alerts" className="mt-4">
          <AlertsTab notifications={notifications} loading={loading} onMarkRead={handleMarkRead} markingId={markingId} />
        </TabsContent>
        <TabsContent value="warnings" className="mt-4"><WarningsTab userId={userId} /></TabsContent>
        <TabsContent value="fines" className="mt-4"><FinesTab userId={userId} /></TabsContent>
      </Tabs>
    </div>
  );
}
