'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Bell,
  AlertTriangle,
  DollarSign,
  CheckCheck,
  Clock,
  Plus,
  Search as SearchIcon,
  Loader2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';

/* ───────── types ───────── */


// Employee for dropdown
interface EmployeeOption {
  id: string;
  fullName: string;
  employeeId: string;
  phone: string | null;
  position: string | null;
  companyName: string | null;
  nationality: string | null;
  currentSite: string | null;
}

// Notification types (warnings/fines)
interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'request' | 'warning' | 'fine';
  read: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Warning {
  id: string;
  employeeId: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Fine {
  id: string;
  employeeId: string;
  reason: string;
  amount: number;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

/* ───────── helpers ───────── */

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-SA', {
    style: 'currency',
    currency: 'SAR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount);
}

/* ───────── Skeleton Cards ───────── */
function SkeletonCards({ count = 3 }: { count?: number }) {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: count }).map((_, i) => (
        <Skeleton key={i} className="h-28 w-full rounded-xl bg-slate-700/50" />
      ))}
    </div>
  );
}

/* ───────── Empty State ───────── */
function EmptyState({ icon: Icon, message }: { icon: React.ElementType; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-700/50 mb-4">
        <Icon className="h-7 w-7 text-slate-500" />
      </div>
      <p className="text-sm text-slate-400">{message}</p>
    </div>
  );
}

/* ───────── Employee Search Combobox (reused) ───────── */
function EmployeeSearchCombobox({
  employees,
  onSelect,
  selectedId,
}: {
  employees: EmployeeOption[];
  onSelect: (emp: EmployeeOption) => void;
  selectedId: string | null;
}) {
  const [open, setOpen] = useState(false);
  const selectedEmployee = useMemo(
    () => employees.find((e) => e.id === selectedId),
    [employees, selectedId]
  );

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between bg-slate-800 border-slate-700 text-white hover:bg-slate-700 hover:text-white text-sm"
        >
          {selectedEmployee
            ? `${selectedEmployee.fullName} (${selectedEmployee.employeeId})`
            : 'Search employees...'}
          <SearchIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0 bg-slate-800 border-slate-600" align="start">
        <Command className="bg-slate-800">
          <CommandInput placeholder="Type to search..." className="text-white" />
          <CommandList>
            <CommandEmpty className="text-slate-400">No employees found.</CommandEmpty>
            <CommandGroup>
              {employees.map((emp) => (
                <CommandItem
                  key={emp.id}
                  value={`${emp.fullName} ${emp.employeeId} ${emp.position || ''}`}
                  onSelect={() => {
                    onSelect(emp);
                    setOpen(false);
                  }}
                  className="text-slate-200 data-[selected=true]:bg-slate-700 data-[selected=true]:text-white"
                >
                  <div className="flex flex-col">
                    <span className="text-sm">{emp.fullName}</span>
                    <span className="text-[11px] text-slate-500">
                      {emp.employeeId}
                      {emp.position ? ` · ${emp.position}` : ''}
                    </span>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

/* ───────── Warnings Tab ───────── */
function WarningsTab({ userId }: { userId: string }) {
  const [warnings, setWarnings] = useState<Warning[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchWarnings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/warnings');
      const data = await res.json();
      if (data.success) {
        setWarnings(data.data.warnings || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch warnings', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchWarnings(); }, [fetchWarnings]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim()) {
      toast({ title: 'Validation Error', description: 'Please select an employee and provide a reason.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/warnings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Warning Issued', description: `Warning has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchWarnings();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue warning', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue warning', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-orange-600 hover:bg-orange-700 text-white text-xs gap-1.5">
          <Plus className="h-3.5 w-3.5" /> Add New Warning
        </Button>
      </div>
      {loading ? <SkeletonCards /> : warnings.length === 0 ? <EmptyState icon={AlertTriangle} message="No warnings found" /> : (
        warnings.map(w => (
          <div key={w.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <span className="text-sm font-semibold text-white truncate">{w.employee.fullName}</span>
                  <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">{w.employee.employeeId}</Badge>
                  {w.isAutoGenerated && <Badge className="text-xs px-2 py-0.5 bg-amber-500/20 text-amber-400 border border-amber-500/30">Auto</Badge>}
                  <Badge className="text-xs px-2 py-0.5 bg-orange-500/20 text-orange-400 border border-orange-500/30"><AlertTriangle className="h-3 w-3 mr-1" />Warning</Badge>
                </div>
                <div className="text-xs text-slate-300 space-y-1">
                  <div><span className="text-slate-500">Reason:</span> {w.reason}</div>
                  {w.absentDates && <div><span className="text-slate-500">Absent dates:</span> {w.absentDates}</div>}
                  <div><span className="text-slate-500">Issued by:</span> {w.createdBy.name}</div>
                </div>
                <div className="mt-2 text-[11px] text-slate-500 flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {formatDate(w.createdAt)}
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Warning Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Warning</DialogTitle>
            <DialogDescription>Issue a warning to an employee. This will deduct 0.5 stars from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the warning" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim()} className="bg-orange-600 hover:bg-orange-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Warning'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Fines Tab ───────── */
function FinesTab({ userId }: { userId: string }) {
  const [fines, setFines] = useState<Fine[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [amount, setAmount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchFines = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/fines');
      const data = await res.json();
      if (data.success) {
        setFines(data.data.fines || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch fines', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchFines(); }, [fetchFines]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    setAmount('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim() || !amount) {
      toast({ title: 'Validation Error', description: 'Please fill in all required fields.', variant: 'destructive' });
      return;
    }
    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount < 0) {
      toast({ title: 'Invalid Amount', description: 'Amount must be a positive number.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/fines', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, amount: numAmount, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Fine Issued', description: `Fine of ${formatCurrency(numAmount)} has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchFines();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue fine', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue fine', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-red-600 hover:bg-red-700 text-white text-xs gap-1.5">
          <Plus className="h-3.5 w-3.5" /> Add New Fine
        </Button>
      </div>
      {loading ? <SkeletonCards /> : fines.length === 0 ? <EmptyState icon={DollarSign} message="No fines found" /> : (
        fines.map(f => (
          <div key={f.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <span className="text-sm font-semibold text-white truncate">{f.employee.fullName}</span>
                  <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">{f.employee.employeeId}</Badge>
                  <Badge className="text-xs px-2 py-0.5 bg-red-500/20 text-red-400 border border-red-500/30"><DollarSign className="h-3 w-3 mr-1" />{formatCurrency(f.amount)}</Badge>
                </div>
                <div className="text-xs text-slate-300 space-y-1">
                  <div><span className="text-slate-500">Reason:</span> {f.reason}</div>
                  <div><span className="text-slate-500">Issued by:</span> {f.createdBy.name}</div>
                </div>
                <div className="mt-2 text-[11px] text-slate-500 flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {formatDate(f.createdAt)}
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Fine Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Fine</DialogTitle>
            <DialogDescription>Issue a fine to an employee. This will deduct 1 star from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Amount (SAR)</Label>
              <Input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" className="bg-slate-900 border-slate-700 text-white" />
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the fine" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim() || !amount} className="bg-red-600 hover:bg-red-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Fine'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Main Page ───────── */
export function NotificationPage() {
  const { user } = useAuthStore();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const userId = user?.id || '';

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await fetch('/api/notifications?limit=100');
      const data = await res.json();
      if (data.success) {
        const notifs: Notification[] = data.data.notifications || [];
        setNotifications(notifs);
        setUnreadCount(notifs.filter((n) => !n.read).length);
      }
    } catch { } finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchNotifications(); }, [fetchNotifications]);

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ markAll: true }) });
      setNotifications(prev => prev.map(n => ({ ...n, read: true })));
      setUnreadCount(0);
      toast({ title: 'All notifications marked as read' });
    } catch { toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' }); }
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10"><Bell className="h-5 w-5 text-blue-400" /></div>
          <div><h2 className="text-2xl font-bold text-white flex items-center gap-2">Notifications{!loading && unreadCount > 0 && <Badge className="bg-blue-500 text-white">{unreadCount}</Badge>}</h2><p className="text-slate-400 text-sm">Stay updated with warnings and fines</p></div>
        </div>
        {unreadCount > 0 && <Button variant="outline" size="sm" onClick={handleMarkAllRead} className="h-8 border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 text-xs"><CheckCheck className="h-3.5 w-3.5 mr-1.5" />Mark All Read</Button>}
      </div>

      <Tabs defaultValue="warnings" className="w-full">
        <TabsList className="bg-slate-800 border border-slate-700/50">
          <TabsTrigger value="warnings" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><AlertTriangle className="h-4 w-4" />Warnings</TabsTrigger>
          <TabsTrigger value="fines" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><DollarSign className="h-4 w-4" />Fines</TabsTrigger>
        </TabsList>

        <TabsContent value="warnings" className="mt-4"><WarningsTab userId={userId} /></TabsContent>
        <TabsContent value="fines" className="mt-4"><FinesTab userId={userId} /></TabsContent>
      </Tabs>
    </div>
  );
}